name: Bump Version (Patch)

on:
    workflow_dispatch:

env:
    NODE_VERSION: 22
    NPM_REGISTRY: https://registry.npmjs.org/

jobs:
    bump-version:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: SetUp Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{env.NODE_VERSION}}
                  registry-url: https://registry.npmjs.org/

            - name: Bump Version (Patch)
              run: |
                  git config --global user.email "getp020506@gmail.com"
                  git config --global user.name "principes-getp"
                  npm version patch
                  git push origin main
